apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: flux
spec:
  template:
    spec:
      containers:
        - name: flux
          envFrom:
            - secretRef:
                name: flux-git-auth
          args:
            - --manifest-generation=true
            - --memcached-hostname=memcached.flux
            - --memcached-service=
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --git-branch=master
            - --git-path=cluster/fluxcd,tenants/acme,tenants/acme
            - --git-user=pgombola
            - --git-email=pgombola@users.noreply.github.com
            - --git-url=https://$(GIT_AUTHUSER):$(GIT_AUTHKEY)@github.com/pgombola/k8s-jenkins
