namespace: template
bases:
  - ../../common
resources:
  - namespace.yaml
configMapGenerator:
  - name: queue-config-cm
    behavior: merge
    literals:
     - queue.url=template
     - queue.length=5
     
