apiVersion: apps/v1
kind: Deployment
metadata:
  name: odie-deployment
  labels:
    app: odie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odie
  template:
    metadata:
      labels:
        app: odie
    spec:
      containers:
      - name: odie
        image: pgombola/odie:1.0
        envFrom:
        - configMapRef:
            name: queue-config-cm
