kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{tenant}}-cie-share-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/clarify"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cie-share-pvc
  namespace: {{tenant}}-cie
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: cie-share-pv
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cie
  namespace: {{tenant}}-cie
  labels:
    app: clarify-worker
spec:
  selector:
    matchLabels:
      app: cie
  template:
    metadata:
      labels:
        app: cie
    spec:
      volumes:
        - name: share
          persistentVolumeClaim:
            claimName: cie-share-pvc
      containers:
      - name: cie
        image: pgombola/cl:deploy-v11
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: '512Mi'
            cpu: '0.5'
          limits:
            memory: '512Mi'
            cpu: '0.5'
        envFrom:
        - secretRef:
            name: rabbitmq-consumer
        env:
        - name: AMQP_URI
          value: 'amqp://user:PASSWORD@rabbitmq.default.svc.cluster.local:5672'
        - name: QUEUE_NAME
          value: {{tenant}}-cie
        volumeMounts:
          - mountPath: '/share'
            name: share
      terminationGracePeriodSeconds: 480
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: cie
  namespace: {{tenant}}-cie
  labels:
    deploymentName: cie
spec:
  scaleTargetRef:
    deploymentName: cie
  pollingInterval: 10   # Optional. Default: 30 seconds
  cooldownPeriod: 30   # Optional. Default: 300 seconds
  maxReplicaCount: 3  # Optional. Default: 100
  minReplicaCount: 0
  triggers:
  - type: rabbitmq
    metadata:
      queueName: hello
      host: RabbitMqHost
      queueLength: '2'
---
