import groovy.json.JsonOutput

pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }
    parameters {
        string(name: 'Tenant Name', defaultValue: '', description: 'Name of tenant to create')
        choice(name: 'Region', choices: ['us-east-1', 'us-west-2'], description: 'Region to deploy tenant')
        choice(name: 'Environment', choices: ['prod', 'stage'], description: 'Environment to deploy tenant')
    }
    environment {
        GIT_CREDENTIAL_ID = 'pgombola-token'
        GIT_URL_WITHOUT_HTTPS = "${GIT_URL}".substring("${GIT_URL}".indexOf('https://')+8)
        GIT_API_URL = "https://api.github.com/repos/pgombola/k8s-jenkins"
        TENANT = "${params['Tenant Name']}"
        TENANT_BRANCH = "tenant-${TENANT}"
    }

    stages {
        stage("Validate parameters") {
            steps {
                script {
                    if (params['Tenant Name'] == '') {
                        error 'Invalid tenant name'
                    }
                }
            }
        }
        stage("Create tenant branch") {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: env.GIT_CREDENTIAL_ID,
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS',)]) {
                    script {
                        def tenantBranch = 'tenant-'+params['Tenant Name']
                        echo "Creating branch ${tenantBranch}"
                        def create = JsonOutput.toJson([ref: "refs/heads/${tenantBranch}", sha: "${GIT_COMMIT}"]).replace("\"", "\\\"")
                        resp = sh (
                            script: "curl -s -o - -i -w \"%{http_code}\" -X POST -d ${create} ${GIT_API_URL}/git/refs -u $USER:$PASS | tail -1",
                            returnStdout: true
                        ).trim()
                        if (resp == '201') {
                            echo 'Branch created.'
                        } else if (resp == '422') {
                            echo 'Branch previously created.'
                        } else {
                            error "Unable to create branch! Status code: ${resp}"
                        }
                    }
                }
            }
        }
        stage("Configure tenant") {
            steps {
                script {
                    def tenant = params['Tenant Name']
                    echo "Configuring ${tenant}..."
                    withCredentials([usernamePassword(
                        credentialsId: env.GIT_CREDENTIAL_ID,
                        usernameVariable: 'USER',
                        passwordVariable: 'PASS')]) {
                        script {
                            env.encodedPass=URLEncoder.encode(PASS, "UTF-8")
                            DIR = "tenant-${tenant}"
                            if (fileExists("${DIR}")) {
                                echo 'Checkout exists in workspace, updating...'
                                dir("${DIR}") {
                                    sh "git pull"
                                }
                            } else {
                                sh "git clone https://${USER}:${encodedPass}@${GIT_URL_WITHOUT_HTTPS} ${DIR} -b tenant-${tenant}"
                                dir("${DIR}") {
                                    bash "./create-tenant.sh ${tenant}"
                                    sh 'git add .'
                                    sh "git commit -m \"Added tenant ${tenant}\""
                                    sh 'git push'
                                }
                            }
                        }
                    }
                }
            }
        }
        stage("Approval") {
            steps {
                echo "creating pr for branch ${TENANT_BRANCH}..."
                withCredentials([usernamePassword(
                    credentialsId: env.GIT_CREDENTIAL_ID,
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS',)]) {
                    script {
                        def create = JsonOutput.toJson([title: "Configure ${TENANT}", head: "${TENANT_BRANCH}", base: "master"]).replace("\"", "\\\"")
                        resp = sh (
                            script: "curl -s -o - -i -w \"%{http_code}\" -X POST -d ${create} ${GIT_API_URL}/pulls -u $USER:$PASS | tail -1",
                            returnStdout: true
                        ).trim()
                        if (resp == '201') {
                            echo 'PR created.'
                        } else {
                            error 'Unable to create PR!'
                        }
                    }
                }
                input message: 'Approve PR', ok: 'Yes'
            }
        }
    }
    post {
        success {
            script {
                if (fileExists("tenant-${params['Tenant Name']}")) {
                    dir ("tenant-${params['Tenant Name']}") {
                        sh "git push origin --delete \"tenant-${params['Tenant Name']}\""
                        deleteDir()
                    }
                }
            }
        }
    }
}